title: "AI Rahman"
description: "AI Rahman demo page"
theme: jekyll-theme-slate

# Customization
markdown: kramdown
highlighter: rouge

# Metadata
author:
  name: "AI Rahman"
  email: "airahmandatasets@gmail.com"
